### ISSUE TITLE
Choosing Glimmer WebComponent crashes ember-cli-crashes

### ISSUE THREAD

**Issue by bracke** [gossi/ember-cli-create#13]
If I choose GlimmerJS web component in the wizard ember-cli-create crashes:

(node:18105) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of 
undefined
    at dasherize (/usr/local/lib/node_modules/ember-cli-create/src/prompts/create-wizard.js:12:13)
    at Object.default (/usr/local/lib/node_modules/ember-cli-create/src/prompts/create-wizard.js:88:12)
    at /usr/local/lib/node_modules/ember-cli-create/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/ember-cli-create/node_modules/run-async/index.js:24:19
    at Object.exports.fetchAsyncQuestionProperty (/usr/local/lib/node_modules/ember-cli-create/node_modules/inquirer/lib/utils/utils.js:21:29)
    at MergeMapSubscriber.obs.pipe.concatMap [as project] (/usr/local/lib/node_modules/ember-cli-create/node_modules/inquirer/lib/ui/prompt.js:73:17)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/ember-cli-create/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/ember-cli-create/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/ember-cli-create/node_modules/rxjs/internal/Subscriber.js:67:18)
(node:18105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gossi** [comment]
Fixed and version `0.0.5` released.

**Comment by bracke** [comment]
Thanks!
I can confirm, it works now :-)
