### ISSUE TITLE
error when i try to use the command

### ISSUE THREAD

**Issue by gilles-bertrand** [gossi/ember-cli-create#3]
When I try to use the command I receive this error

node:25496) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, uv_chdir
    at Observable (/home/gilles/.config/yarn/global/node_modules/ember-cli-create/src/commands/create.js:209:12)
    at new Subscription (/home/gilles/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:179:34)
    at Observable.subscribe (/home/gilles/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:258:14)
    at Promise (/home/gilles/.config/yarn/global/node_modules/listr/lib/task.js:130:13)
    at new Promise (<anonymous>)
    at handleResult (/home/gilles/.config/yarn/global/node_modules/listr/lib/task.js:129:14)
    at Promise.resolve.then.then.skipped (/home/gilles/.config/yarn/global/node_modules/listr/lib/task.js:167:12)
    at <anonymous>

I'm using node with nvm

**Comment by gossi** [comment]
I have seen this error, too. Though don't know why yet. Did you try to run the command a second time?

**Comment by gilles-bertrand** [comment]
Yes I tried with different node version too my ember version is 3.3

Télécharger Outlook pour Android<https://aka.ms/ghei36>




On Tue, Aug 21, 2018 at 10:53 PM +0200, "Thomas Gossmann" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have seen this error, too. Though don't know why yet. Did you try to run the command a second time?

**Comment by gossi** [comment]
Ok, so for the next version. I will make a check to see if the ember create project command run fine.

**Comment by gilles-bertrand** [comment]
Great , just for info I'm on ubuntu
